language: c

before_install:
   - sudo apt-get update -qq
   - sudo apt-get install libgstreamer1.0-dev
   - gst-inspect-1.0 --version

script:
   - mkdir -p build
   - cd build
   - cmake ../ && make && ctest
