language: c

before_install:
   - sudo apt-get update -qq
   - sudo apt-get remove libgstreamer1.0-0
   - sudo apt-get install autoconf automake autopoint pkg-config libtool bison flex
   - git clone https://github.com/GStreamer/gstreamer.git -b 1.8.3 gstreamer
   - cd gstreamer
   - ./autogen.sh --disable-gtk-doc --prefix=/usr/ && make -j 4 && sudo make install
   - cd ../
   - gst-inspect-1.0 --version
   - sudo -H pip install pip -U
   - sudo -H pip install cpp-coveralls -U

script:
   - mkdir -p build
   - cd build
   - cmake --version && cmake ../ -DENABLE_COVERAGE=1 && make -j 4 && ctest -V
   
after_success:
   - coveralls
